# myproc:myproc.c
# 	gcc -o $@ $^ -std=c99 
# .PHONY: clean
# clean:
# 	rm -f myproc
# file1:file1.c
# 	gcc -o $@ $^ -std=c99
# .PHONY: clean
# clean:
# 	rm -f file1

# mychild:mychild.c
# 	gcc -o $@ $^ -std=c99
# .PHONY: clean
# clean:
# 	rm -f mychild

# myexec:myexec.c
# 	gcc -o $@ $^ -std=c99
# .PHONY: clean
# clean:
# 	rm -f myexec
# .PHONY:all
# all:mybin myexec

# myexec:myexec.c
# 	gcc -o $@ $^ -std=c99
# mybin:mybin.c
# 	gcc -o $@ $^ -std=c99
# .PHONY: clean
# clean:
# 	rm -f myexec mybin

myshell:myshell.c
	gcc -o $@ $^ -std=c99 
.PHONY: clean
clean:
	rm -f myshell


